version: "3.9"

services:

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: trademind
      POSTGRES_PASSWORD: trademind
      POSTGRES_DB: trademind_db
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://trademind:trademind@db:5432/trademind_db
      SECRET_KEY: supersecretkey
      NEWS_API_KEY: ce19dd41f65c4ad49127b257ce528281

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend